server:
  port: 6000
spring:
  application:
    name: PLAT
eureka:
  client:
    service-url:
      defaultZone: http://eureka-7001:7001/eureka/ #告诉服务提供者要把服务注册到哪儿 #单机环境
  instance:
    prefer-ip-address: true
    instance-id: plat
